# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Marta Morandini
# Description of the Site
description: Mathematician swimming in Computational Neuroscience
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/background_picture.jpg"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mm.martamorandini@gmail.com
#facebook_username: /
twitter_username: martasolves_
linkedin_username: martamorandini
scholar_userid: E4Hje4QAAAAJ&hl=it&oi=ao
#instagram_username: /
github_username:  MartaMorandini
orcid_id: 0009-0005-0324-6094
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Marta Morandini
# URL for the Image of the Author
author-image: "/assets/images/profile_picture.jpg"
# 60 Words About the Author
author-about: Currently pursuing a PhD in Neuroscience, under the supervision of Andrea Brovelli and Matthieu Gilson, at the INT in Marseille. Mathematician by training, I have always been interested in merging theories and applications, in particular through complex systems, information theory and topological data analysis.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MartaMorandini

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
