# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Marta Morandini
# Description of the Site
description: Mathematician swimming in Computational Neuroscience
# URL of Image of the Site
site-image: /assets/images/logo.png
# Keywords of the Site
site-keywords: Complex Systems, Computational Neuroscience
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/background_picture.jpg"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mm.martamorandini@gmail.com
#facebook_username: /
twitter_username: martasolves_
linkedin_username: martamorandini
scholar_userid: E4Hje4QAAAAJ&hl=it&oi=ao
#instagram_username: /
github_username:  MartaMorandini
orcid_id: 0009-0005-0324-6094
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Marta Morandini
# URL for the Image of the Author
author-image: "/assets/images/profile_picture.jpg"
# 60 Words About the Author
author-about: I am currently pursuing my PhD in Neuroscience under the supervision of<a href="https://scholar.google.com/citations?user=vsskO0AAAAAJ&hl=fr" style="color:#c9a0dc;">Andrea Brovelli</a>and<a href="https://matthieugilson.eu/" style="color:#c9a0dc;">Matthieu Gilson</a>, at the<a href="https://www.int.univ-amu.fr/" style="color:#c9a0dc;">Institut de Neurosciences de la Timone</a>(Marseille), in<a href="https://brainets.github.io/" style="color:#c9a0dc;">BraiNets</a>team. I have always been fascinated by the intersection of theory and applications - such as the human brain - through complex systems, information theory and topology.<br><br>I previously obtained my MSc in Mathematics from the University of Turin. For my final thesis, I had the opportunity to intern at the<a href="https://centai.eu/home" style="color:#c9a0dc;">CENTAI Insitute</a>, where I worked in the<a href="https://nplresearch.github.io/" style="color:#c9a0dc;">NPL</a>under the supervision of<a href="https://lordgrilo.github.io/" style="color:#c9a0dc;">Giovanni Petri</a>.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MartaMorandini

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/